### PR TITLE
Add [v1] events commands

### PR DESCRIPTION
**Pull request by bryfox**
This adds new top-level `events` commands which use v1 of the API. The beta events commands are extant but now print a deprecation warning to stderr. I did not spend time removing duplication between the two; the old code exists in new files which is easily removed once we're ready to.

Reference docs: https://foxglove.dev/docs/api#tag/Events

### CODE REVIEW

**Comment by wkalt** [comment]
Should we retire "beta events" right away, or add support for this new thing and deprecate the old thing for a while (perhaps with a warning to stderr or something)? The old beta endpoint will presumably be around for some time, since we have old client versions.

**Comment by bryfox** [comment]
I updated to keep the beta version around with a deprecation warning.

**Comment by wkalt** [comment]
@bryfox how does the map appear in the rendering?

**Comment by bryfox** [comment]
> how does the map appear in the rendering?

JSON, same as the original version:

https://github.com/foxglove/foxglove-cli/blob/1c547c28f011481e3e201a034eac978bddc9eaec/foxglove/console/api.go#L175-L176

**Comment by bryfox** [comment]
I resolved conflicts with attachments additions on main.

**Pull request merged**
